<?php namespace ProcessWire;

/**
 * Class AlpineJS
 *
 */

class AlpineJS extends ModuleJS implements Module {

		public static function getModuleInfo() {
				return array(
					'title' => 'Alpine.js',
					'version' => 001,
					'href' => 'http://alpinejs.dev',
				);
		}

		public function getVersionUrl(){
				$class = $this->className();
				return "{$this->config->urls->$class}alpinejs/{$this->version}/alpine.js";
		}

		public function init() {
				$config = $this->config;
				$config->scripts->add($this->getVersionUrl(), ['defer' => true]);
		}

}
